### ISSUE TITLE
Add Wiki markdown

### ISSUE THREAD

**Issue by soumik2012** [Tenet-Coding/ArtofCoding#23]
## 🚀 Feature

Add a  Wiki Markdown of ` What is a Pull Request and how to do it? ` you can refer from [here](https://github.com/TesseractCoding/NeoAlgo/wiki/What-is-a-Pull-Request-and-how-to-do-it%3F)
@Harshil-Jani can you take this issue ?

**Comment by Harshil-Jani** [comment]
Yes, I can.

**Comment by Harshil-Jani** [comment]
@soumik2012 Let me know if changes are required.
