### ISSUE TITLE
 Valid Palindrome

### ISSUE THREAD

**Issue by soumikbaithalu** [Tenet-Coding/ArtofCoding#30]
## 🚀 Feature

Given a string s, determine if it is a palindrome, considering only alphanumeric characters and ignoring cases

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/Tenet-Coding/ArtofCoding/blob/main/CONTRIBUTING.md)?

yes

## Pitch
Example 1:

Input: s = "A man, a plan, a canal: Panama"
Output: true
Explanation: "amanaplanacanalpanama" is a palindrome.

**Comment by SanthoshS20** [comment]
@soumik2012 Do you need it in all languages mentioned? Can I contribute this Issue on C, C++, Python language?

**Comment by soumik2012** [comment]
- It depends upon you @SanthoshS20 if you can solve the question in all the languages.
- Yes, you can.

**Comment by Nishith-Gohel** [comment]
Hello @soumik2012 I can contribute towards validating the palindrome using **C++**, with proper explanation through comments.
Could you assign the task to me ?
