### ISSUE TITLE
Restyled.io Removal Request!

### ISSUE THREAD

**Issue by Harshil-Jani** [Tenet-Coding/ArtofCoding#35]
## 🐛 Bug Report

I want to ask can we remove Restyle.io ? Because It is just creating some extra spaces which in general are not in practice even in real world software companies. Developers prefer less spaces in code. It tries making code neat but, always creates PR issues. If possible can we remove it?

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/Tenet-Coding/ArtofCoding/blob/main/CONTRIBUTING.md)?

Yes.

**Comment by soumik2012** [comment]
@Harshil-Jani No, we can remove the restyle.io real-world companies also maintain clean and neat code. Since you can see that it does not rewrite your code simple add some same and remove some extra space so it will maintain the memory of code as same.
