### ISSUE TITLE
3Sum

### ISSUE THREAD

**Issue by sahilsingh7735** [Tenet-Coding/ArtofCoding#53]
## Problem Statement
Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.

Notice that the solution set must not contain duplicate triplets.

 

Example 1:

Input: nums = [-1,0,1,2,-1,-4]
Output: [[-1,-1,2],[-1,0,1]]
Example 2:

Input: nums = []
Output: []
Example 3:

Input: nums = [0]
Output: []
 

Constraints:

0 <= nums.length <= 3000
-105 <= nums[i] <= 105

**Comment by soumik2012** [comment]
Go ahead @sahilsingh7735

**Comment by soumik2012** [comment]
@pragatisaikia  Yes, you can!!

**Comment by soumik2012** [comment]
@Poojasingh5 Yes you can!!
