### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by seraph776** [Tenet-Coding/ArtofCoding#72]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

The link to the issues template: `/ISSUE_TEMPLATE/algorithm-ds-proposal.md`  on the `README.md` file under _Contributing Guidelines_ is broken [`404 Error`] . 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/Tenet-Coding/ArtofCoding/blob/main/CONTRIBUTING.md)?
- Yes 👍🏽

**Comment by Harshil-Jani** [comment]
@seraph776 Thanks for notifying. We can do two things for the same. 
1.) Create an `algotithm-ds-proposal.md` file in the `ISSUE_TEMPLATE` directory with required  details.
2.) Change the link from `algorithm-ds-proposal.md` to`feature-request---.md`

Would you like to take this up ?

**Comment by seraph776** [comment]
Yes, I'll complete this task!

**Comment by seraph776** [comment]
Issue resolved!
