### ISSUE TITLE
JavaScript Problem 

### ISSUE THREAD

**Issue by soumikbaithalu** [Tenet-Coding/ArtofCoding#9]
Add the Folder of JavaScript and then add other which problem is related like it's an if the problem is related to backtracking and add a folder of backtracking if the problem is related to Dynamic Programming the add the folder of Dynamic programming, etc.

**Comment by 2brownc** [comment]
Can I work on it?

**Comment by soumikbaithalu** [comment]
> Can I work on it?

Yes you can @2brownc
